# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        name: merge-to-master
        runs-on: ubuntu-latest
    
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
                run: |
                    pip install -r requirements
            - name: Run tests
                run: |
                cd tests
                python test_all.py
